from enum import Enum

from aiogram.filters.callback_data import CallbackData as BaseCallback

class CallbackData(str, Enum):
    SHOW_EMAIL = "SHOW_EMAIL"
    START_CHAT = "START_CHAT"
    BACK_TO_MENU = "BACK_TO_MENU"
    BACK_TO_SERVICES = "BACK_TO_SERVICES"
    ORDER_START = "ORDER_START"
    HELP = "HELP"
    FAQ_CONTENT = "FAQ_CONTENT"
    FAQ = "FAQ"
    ORDER_QUIZ_QUESTIONS = "ORDER_QUIZ_QUESTIONS"
    ABOUT_US = "ABOUT_US"
    CONTACT_MANAGER = "CONTACT_MANAGER"
    MAIN_MENU = "MAIN_MENU"
    MAIN_MENU_ABOUT = "🏢 О нас"
    MAIN_MENU_SERVICES = "🛠 Услуги"
    MAIN_MENU_ORDER_WEBSITE = "🌐 Заказать сайт"
    MAIN_MENU_MANAGER = "👨‍💼 Связаться с менеджером"
    MAIN_MENU_CHAT = "💬 Начать чат"
    MAIN_MENU_FAQ = "❓ FAQ"

    ORDER_WEBSITE = "ORDER_WEBSITE"
    CANCEL_ORDER = "CANCEL_ORDER"

    SERVICES = "SERVICES"
    SERVICE_DEVELOPMENT_DESIGN = "SERVICE_DEVELOPMENT_DESIGN"
    SERVICE_DEVELOPMENT_DESIGN_WORDPRESS = "SERVICE_DEVELOPMENT_DESIGN_WORDPRESS"
    SERVICE_DEVELOPMENT_DESIGN_NEXT = "SERVICE_DEVELOPMENT_DESIGN_NEXT"
    SERVICE_DEVELOPMENT_DESIGN_WEBFLOW = "SERVICE_DEVELOPMENT_DESIGN_WEBFLOW"
    SERVICE_DEVELOPMENT_DESIGN_UIUX = "SERVICE_DEVELOPMENT_DESIGN_UIUX"
    SERVICE_DEVELOPMENT_DESIGN_SUPPORT = "SERVICE_DEVELOPMENT_DESIGN_SUPPORT"

    SERVICE_SEO = "SERVICE_SEO"
    SERVICE_SEO_AUDIT = "SERVICE_SEO_AUDIT"
    SERVICE_SEO_PACKAGE = "SERVICE_SEO_PACKAGE"
    SERVICE_SEO_LOCAL = "SERVICE_SEO_LOCAL"

    SERVICE_MARKETING = "SERVICE_MARKETING"
    SERVICE_MARKETING_GOOGLE = "SERVICE_MARKETING_GOOGLE"
    SERVICE_MARKETING_YANDEX = "SERVICE_MARKETING_YANDEX"
    SERVICE_MARKETING_SMM = "SERVICE_MARKETING_SMM"

    SERVICE_FASTSTART = "SERVICE_FASTSTART"
    SERVICE_FASTSTART_LANDING24 = "SERVICE_FASTSTART_LANDING24"
    SERVICE_FASTSTART_EXPRESS = "SERVICE_FASTSTART_EXPRESS"
    SERVICE_FASTSTART_INTEGRATION = "SERVICE_FASTSTART_INTEGRATION"

    SERVICE_SPECIFIC = "SERVICE_SPECIFIC"
    NEW_REQUEST = "NEW_REQUEST"

    NEW_ORDER = "NEW_ORDER"

    SERVICE_CORPORATE = "SERVICE_CORPORATE"
    SERVICE_LANDING = "SERVICE_LANDING"
    SERVICE_SHOP = "SERVICE_SHOP"
    SERVICE_CATALOG = "SERVICE_CATALOG"
    SERVICE_REDESIGN = "SERVICE_REDESIGN"
    SERVICE_SUPPORT = "SERVICE_SUPPORT"
    SUBMIT_REQUEST = "SUBMIT_REQUEST"


COMPANY_INFO = {
    "name": "WWWizards",
    "email": "info@example.com",
    "website_ru":"https://google.ru",
    "website_com":"https://google.com",
    "telegram":"@WWWizardsbot",
    "description":"Description about the company",
    "tg_support_channel_id":"-1002912834496"
}
